version: "0.2"
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre-build:
    commands:
      - edho "Installing depends on"
      - cd angular-ws
      - npm ci
      - npm i -g nx
  build:
    commands:
      - echo "Start compilation"
      - npx nx run-many --target=build --all --skip-nx-cache
  post_build:
    commands:
      - aws s3 rm s3://microfrontends02 --recursive
      - aws s3 sync dist/apps/ambulance-menu/browser s3://microfrontends02 --delete
artifacts:
  name: "mfe"
  files:
    - "**/*"
  base-directory: dist/apps/ambulance-menu/browser